use_frameworks!

platform :ios, '11.0'

target 'FearthGdk_Example' do
  pod 'FearthGdk', :path => '../'

  target 'FearthGdk_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
