# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'fearth-ios-gdk-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Using local pod
   pod 'FearthGdk', :path => '../'

  # Using git repo
  # pod 'FearthGdk', :git => 'https://github.com/phucanh1939/fearth-ios-gdk.git', :tag => 'v0.6.0'
  
  # Using published pod on cocoapods
#  pod 'FearthGdk', '~> 0.6'
end
