# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'fearth-ios-gdk-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fearth-ios-gdk-sample
  pod 'FearthGdk', :path => '../'
  # pod 'FearthGdk', '~> 0.4'

end
